# https://circleci.com/docs/2.0/language-javascript/
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13

jobs:
  test_and_docs:
    docker:
      - image: circleci/node:12.13.0
        environment:
          DATABASE_USER: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_HOST: 127.0.0.1
          DATABASE_NAME: players
          DATABASE_PORT: 5432
          POSTGRES_MAX: 800
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: players
    working_directory: ~/crm-service
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Download Swagger UI
          command: |
            if [ ! -d "swagger-ui-3.22.0" ]; then
              wget -qO- https://github.com/swagger-api/swagger-ui/archive/v3.22.0.tar.gz | tar xvz
            fi
      - run:
          name: Install Flyway
          command: |
            if [ ! -d "flyway-5.2.4" ]; then
              wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/5.2.4/flyway-commandline-5.2.4-linux-x64.tar.gz | tar xvz
            fi
            sudo ln -s `pwd`/flyway-5.2.4/flyway /usr/local/bin
      - run:
          name: Install Dependencies
          command: yarn install --network-concurrency 1
      - save_cache:
          paths:
            - flyway-5.2.4
            - node_modules
            - swagger-ui-3.22.0
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run Migrations
          command: ./bin/db-migrate
      - run:
          name: Build
          command: yarn build
      - run:
          name: Lint
          command: yarn test:lint
      - run:
          name: Test
          command: yarn test:unit
      - run:
          name: Generate Coverage Report
          command: yarn run cov:html
      - run:
          name: Check Coverage Report
          command: yarn run cov:check
      - run:
          name: Generate Code Documentation
          command: yarn run doc:html
      - run:
          name: Generate Swagger Documentation
          command: |
            sed -i -e 's/https\:\/\/petstore.swagger.io\/v2\/swagger.json/api.yaml/g' swagger-ui-3.22.0/dist/index.html
            cp swagger/api.yaml swagger-ui-3.22.0/dist/api.yaml
      - store_artifacts:
          path: coverage
          destination: coverage
      - store_artifacts:
          path: build/docs
          destination: docs
      - store_artifacts:
          path: swagger-ui-3.22.0/dist
          destination: swagger
      - persist_to_workspace:
          root: .
          paths:
            - build/main
            - db/migration
            - Dockerfile
            - Dockerfile_migrations
            - newrelic.js
            - node_modules

workflows:
  version: 2
  test_and_push:
    jobs:
      - test_and_docs:
          filters:
            tags:
              only: /^v.*/
      - push_latest:
          requires:
            - test_and_docs
          filters:
            branches:
              only:
                - master
      - push_tag:
          requires:
            - test_and_docs
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
